#!/usr/bin/env bash
# updateme installer
# Usage: curl -fsSL https://raw.githubusercontent.com/ca1ebd/updateme/main/install.sh | bash

set -euo pipefail

REPO_RAW="${REPO_RAW:-https://raw.githubusercontent.com/ca1ebd/updateme/main}"
INSTALL_DIR="${HOME}/.local/share/updateme"
BIN_DIR="${HOME}/.local/bin"
WRAPPER="${BIN_DIR}/updateme"
VENV_DIR="${INSTALL_DIR}/.venv"

# ── Colours ───────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  GREEN=$'\e[32m'; YELLOW=$'\e[33m'; CYAN=$'\e[36m'; BOLD=$'\e[1m'; RESET=$'\e[0m'
else
  GREEN=''; YELLOW=''; CYAN=''; BOLD=''; RESET=''
fi

info()  { printf "${CYAN}  →${RESET} %s\n" "$*"; }
ok()    { printf "${GREEN}  ✓${RESET} %s\n" "$*"; }
warn()  { printf "${YELLOW}  ⚠${RESET}  %s\n" "$*"; }
die()   { printf "  ✗ %s\n" "$*" >&2; exit 1; }

echo ""
printf "${BOLD}  updateme installer${RESET}\n"
echo "  ─────────────────"
echo ""

# ── Dependency check ──────────────────────────────────────────────────────────
command -v python3 &>/dev/null || die "python3 is required. Install it and re-run."
PY_OK=$(python3 -c "import sys; print(sys.version_info >= (3, 8))")
[[ "$PY_OK" == "True" ]] || die "Python 3.8+ is required."

# ── Download ──────────────────────────────────────────────────────────────────
info "Installing to ${INSTALL_DIR} ..."
mkdir -p "${INSTALL_DIR}/modules"

FILES=(
  updateme.py
  config.py
  config.yml
  modules/__init__.py
  modules/weather.py
  modules/headlines.py
  modules/markets.py
)

for f in "${FILES[@]}"; do
  python3 -c "
import urllib.request, os, sys
url  = sys.argv[1]
dest = sys.argv[2]
os.makedirs(os.path.dirname(dest), exist_ok=True)
urllib.request.urlretrieve(url, dest)
" "${REPO_RAW}/${f}" "${INSTALL_DIR}/${f}"
done
chmod +x "${INSTALL_DIR}/updateme.py"
ok "Downloaded ${#FILES[@]} files"

# ── Virtual environment + pyyaml ──────────────────────────────────────────────
info "Setting up Python environment ..."
if command -v uv &>/dev/null; then
  uv venv --quiet "${VENV_DIR}"
  uv pip install --quiet --python "${VENV_DIR}/bin/python" pyyaml
else
  python3 -m venv "${VENV_DIR}"
  "${VENV_DIR}/bin/pip" install --quiet pyyaml
fi
ok "Dependencies installed (pyyaml)"

# ── Wrapper ───────────────────────────────────────────────────────────────────
mkdir -p "${BIN_DIR}"
printf '#!/usr/bin/env bash\n# updateme wrapper — generated by installer\nexec "%s/bin/python" "%s/updateme.py" "$@"\n' \
  "${VENV_DIR}" "${INSTALL_DIR}" > "${WRAPPER}"
chmod +x "${WRAPPER}"
ok "Wrapper created at ${WRAPPER}"

# ── PATH ──────────────────────────────────────────────────────────────────────
PATH_LINE='export PATH="${HOME}/.local/bin:${PATH}"'

add_to_rc() {
  local rc="$1"
  grep -q '\.local/bin' "${rc}" 2>/dev/null && return 0
  printf '\n# Added by updateme installer\n%s\n' "${PATH_LINE}" >> "${rc}"
  ok "Added ~/.local/bin to PATH in ${rc}"
}

SHELL_NAME="$(basename "${SHELL:-bash}")"
if [[ "$(uname)" == "Darwin" ]]; then
  [[ "${SHELL_NAME}" == "zsh" ]] && add_to_rc "${HOME}/.zshrc" || add_to_rc "${HOME}/.bash_profile"
else
  add_to_rc "${HOME}/.bashrc"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
ok "updateme installed!"
echo ""
printf "  ${BOLD}Configure:${RESET}  edit %s\n" "${INSTALL_DIR}/config.yml"
if ! command -v updateme &>/dev/null 2>&1; then
  printf "\n  ${YELLOW}Reload your shell first:${RESET}\n"
  [[ "${SHELL_NAME}" == "zsh" ]] \
    && printf "    source ~/.zshrc\n" \
    || printf "    source ~/.bashrc\n"
fi
echo ""
printf "  Then run:  ${BOLD}updateme${RESET}\n"
echo ""
