#!/usr/bin/env bash
# updateme installer
# Usage: curl -fsSL https://raw.githubusercontent.com/ca1ebd/updateme/main/install.sh | bash

set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/ca1ebd/updateme/main"
INSTALL_DIR="${HOME}/.local/share/updateme"
BIN_DIR="${HOME}/.local/bin"
WRAPPER="${BIN_DIR}/updateme"

# ── Colours ────────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  GREEN=$'\e[32m'; YELLOW=$'\e[33m'; CYAN=$'\e[36m'; BOLD=$'\e[1m'; RESET=$'\e[0m'
else
  GREEN=''; YELLOW=''; CYAN=''; BOLD=''; RESET=''
fi

info()  { printf "${CYAN}  →${RESET} %s\n" "$*"; }
ok()    { printf "${GREEN}  ✓${RESET} %s\n" "$*"; }
warn()  { printf "${YELLOW}  ⚠${RESET}  %s\n" "$*"; }
die()   { printf "  ✗ %s\n" "$*" >&2; exit 1; }

echo ""
printf "${BOLD}  updateme installer${RESET}\n"
echo "  ─────────────────"
echo ""

# ── OS detection ───────────────────────────────────────────────────────────────
OS="linux"
[[ "$(uname)" == "Darwin" ]] && OS="macos"

# ── Dependency checks ──────────────────────────────────────────────────────────
command -v curl   &>/dev/null || die "curl is required. Install it and re-run."
command -v python3 &>/dev/null || die "python3 is required. Install it and re-run."

# Bash version check — macOS ships bash 3.2; we need 4+ for mapfile
BASH_MAJOR="${BASH_VERSINFO[0]}"
if [[ "$BASH_MAJOR" -lt 4 ]]; then
  warn "Your bash is version ${BASH_VERSION} (need 4+)."
  if [[ "$OS" == "macos" ]]; then
    warn "Install a modern bash via Homebrew, then re-run:"
    warn "  brew install bash"
  fi
  die "Aborting — please upgrade bash first."
fi

# ── Download ───────────────────────────────────────────────────────────────────
info "Installing to ${INSTALL_DIR} ..."
mkdir -p "${INSTALL_DIR}/modules"

FILES=(
  updateme.sh
  config.sh
  modules/weather.sh
  modules/headlines.sh
  modules/markets.sh
)

for f in "${FILES[@]}"; do
  curl -fsSL "${REPO_RAW}/${f}" -o "${INSTALL_DIR}/${f}"
done
chmod +x "${INSTALL_DIR}/updateme.sh"
ok "Downloaded $(echo "${#FILES[@]}") files"

# ── Wrapper ────────────────────────────────────────────────────────────────────
mkdir -p "${BIN_DIR}"
cat > "${WRAPPER}" << WRAPPER_BODY
#!/usr/bin/env bash
# updateme wrapper — generated by installer
exec bash "${INSTALL_DIR}/updateme.sh" "\$@"
WRAPPER_BODY
chmod +x "${WRAPPER}"
ok "Wrapper created at ${WRAPPER}"

# ── PATH ───────────────────────────────────────────────────────────────────────
# Add ~/.local/bin to PATH in the appropriate shell rc if not already present
PATH_LINE='export PATH="${HOME}/.local/bin:${PATH}"'

add_to_rc() {
  local rc="$1"
  if grep -q '\.local/bin' "${rc}" 2>/dev/null; then
    return 0  # already present
  fi
  printf '\n# Added by updateme installer\n%s\n' "${PATH_LINE}" >> "${rc}"
  ok "Added ~/.local/bin to PATH in ${rc}"
}

SHELL_NAME="$(basename "${SHELL:-bash}")"
if [[ "${OS}" == "macos" ]]; then
  if [[ "${SHELL_NAME}" == "zsh" ]]; then
    add_to_rc "${HOME}/.zshrc"
  else
    add_to_rc "${HOME}/.bash_profile"
  fi
elif grep -qi microsoft /proc/version 2>/dev/null; then
  # WSL
  add_to_rc "${HOME}/.bashrc"
else
  # Linux
  add_to_rc "${HOME}/.bashrc"
fi

# ── Done ───────────────────────────────────────────────────────────────────────
echo ""
ok "updateme installed!"
echo ""
printf "  ${BOLD}Configure:${RESET}  edit %s\n" "${INSTALL_DIR}/config.sh"
if ! command -v updateme &>/dev/null 2>&1; then
  printf "\n  ${YELLOW}Reload your shell first:${RESET}\n"
  if [[ "${SHELL_NAME}" == "zsh" ]]; then
    printf "    source ~/.zshrc\n"
  else
    printf "    source ~/.bashrc\n"
  fi
fi
echo ""
printf "  Then run:  ${BOLD}updateme${RESET}\n"
echo ""
